name: Android Release Build

on:
  push:
    tags:
      - 'v0*' # Executa quando um tag começando com "v" é feita (ex: v1.3.0)


jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Prebuild Expo
        run: npx expo prebuild --non-interactive --platform android

      - name: Build APK
        run: |
          cd android
          ./gradlew assembleRelease
        env:
          EXPO_NO_COMMAND: 1

      - name: Upload APK to Release
        uses: softprops/action-gh-release@v1
        with:
          files: android/app/build/outputs/apk/release/app-release.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: listadecompras-release.apk
          path: android/app/build/outputs/apk/release/app-release.apk
          if-no-files-found: error
          overwrite: true
